template = ""
rev_id = 4
template_sha = "156a8b834dacf74fc905a1ee460fe5eabb9556c6"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "fkv"
__UND2C_TRG__ = "nb"
__UNDEFINED_SOURCE__ = "Kven"
__UNDEFINED_TARGET__ = "Norwegian Bokm√•l"
__UND_SRC__ = "fkv"
__UND_TRG__ = "nob"
